---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitlab-runner
  namespace: flux-system
spec:
  path: ./kubernetes/apps/gitlab-space/gitlab-runner/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: secretsy-infra
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
