---
creation_rules:
  - path_regex: .*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData|externalName|tls|rules|value|key)$"
    key_groups:
      - age:
        - age17nr093c37k5732q9ksxf2p785wd9fxjej7axzcn66lm6muys0eks9kmzts  # Daniel
