apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labels
labels:
  app.kubernetes.io/usage: gitlab
  toolkit.fluxcd.io/tenant: devops-team
fieldSpecs:
  - path: metadata/labels
    create: true
