---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dex
  namespace: dapr-system
spec:
  interval: 15m
  chart:
    spec:
      chart: dex
      version: "0.24.0"
      sourceRef:
        kind: HelmRepository
        name: dex
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  # https://github.com/dexidp/helm-charts/tree/dex-0.24.0/charts/dex
  values:
    commonLabels:
      toolkit.fluxcd.io/tenant: devops-team
      app.kubernetes.io/part-of-system: *app
    config:
      # Set it to a valid URL
      issuer: http://my-issuer-url.com

      # See https://dexidp.io/docs/storage/ for more options
      storage:
        type: memory

      # Enable at least one connector
      # See https://dexidp.io/docs/connectors/ for more options
      enablePasswordDB: true
