---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dapr
  namespace: dapr-system
spec:
  interval: 15m
  chart:
    spec:
      chart: dapr
      version: "1.16"
      sourceRef:
        kind: HelmRepository
        name: dapr
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    global:
      labels:
        toolkit.fluxcd.io/tenant: devops-team
        app.kubernetes.io/part-of-system: *app
