---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/dxas90/basedapr.git
  ref:
    branch: main
  ignore: |
    # exclude
    /*
    # include
    !/clusters
    !/homelab
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-apps
  namespace: flux-system
spec:
  interval: 30m
  path: ./homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/metal
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab

  # kubectl apply --server-side -k bootstrap; \
  # kubectl apply -f clusters/metal/gotk-sync.yaml
