---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-apps
  namespace: flux-system
spec:
  interval: 30m
  path: ./common
  prune: true
  sourceRef:
    kind: GitRepository
    name: basedapr
