---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app istio-cni
  namespace: istio-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/base: *app
  interval: 15m
  targetNamespace: istio-system
  chart:
    spec:
      chart: cni
      version: 1.28.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    ambient:
      enabled: true
    global:
      platform: k3s
    # cniConfDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
    # cniBinDir: /var/lib/rancher/k3s/data/cni
    # cni:
    #   nativeNftables: true
